---
name: Continuos Deployment

on:
  push:
    branches:
      - master
      - production
  pull_request: 

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "sleep 7;python manage.py test"

  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
  
  deploy-staging:
    name: Deploy to staging
    runs-on: ubuntu-20.04
    needs: [test, lint]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Staging
        run: echo "Deploy to STAGING code here"
  
  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-20.04
    needs: [test, lint]
    if: github.ref == 'refs/heads/production'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Production
        run: echo "Deploy to PRODUCTION code here"



